### ISSUE TITLE
怪物节点的相关bug

### ISSUE THREAD

**Issue by raining976** [raining976/cocos-rougelike-game#39]
- 死亡后不会立即回收,这就导致如果不判断怪物当前血量直接扣血的话这个节点再次生成时并不是满血
- 回收时空血的怪物会从死亡位置瞬移到新生成的位置
- 新生成的位置离死亡位置很近,随机位置的问题应该是

**Comment by chenlan7064** [comment]
再次生成怪物不是满血并非是由于死亡后没有立刻回收，而是由于怪物节点自对象池取出后，碰撞体不同步在怪物生成位置生成而会从死亡位置移动到怪物生成位置，中间穿过转刀则会触发碰撞监听。通过将新怪物节点延时设置为满血，将复用怪物节点死亡前重设为随机坐标，该bug暂时解决

采用了新的坐标生成逻辑以及节点复用逻辑后下面两个bug也已被解决，最新提交中暂时未复现相关bug
