### ISSUE TITLE
升级面板

### ISSUE THREAD

**Issue by raining976** [raining976/cocos-rougelike-game#44]
- 每升一级提升某一方面的属性(武器数量,人物血量,技能, 并且能显示当前和下一级的值)
- 选项卡选择要升级的属性
- 尽量加一个选项卡出现和消失的过渡
![升级面板](https://github.com/raining976/cocos-rougelike-game/assets/92510214/e33aa83b-64ad-4c0f-94b8-8f4918312a6e)

**Comment by Tttdotd** [comment]
完成了升级弹出选项面板，可以从三种属性中选择一种进行增强。
