### ISSUE TITLE
怪物相关

### ISSUE THREAD

**Issue by raining976** [raining976/cocos-rougelike-game#46]
- 完善现有功能
- 解决已有的bug

**Comment by chenlan7064** [comment]
11.26 refactor:增加多样化角色，修正回收再生成的怪物不是满血的bug，数值平衡调整。动画制作，怪物预制体制作，怪物状态机设计，添加statebase（状态基类）、statexxx（状态类）、Animator(动画机类，管理单个角色的状态）

12.2 fix:1.新建Randompos脚本，集成了坐标随机生成相关功能，优化了坐标生成相关逻辑2.消除了节点回收时碰撞体不同步导致的生成残血敌人bug3.调整项目结构

12.5 refactor:完全实现状态模式，应用FSM对敌人状态进行管理。通过应用状态模式，将敌人行为封装至状态对象中，有利于后续程序的扩展，能很容易地配置和修改不同敌人的个性化行为，极大地提高了代码的灵活性、可重用性、可读性、扩展性与可维护性

12.11 fix:1.修改清屏和视野外敌人回收逻辑 2.解决投射物的方向bug 3.增加投射物的碰撞体 4.修改敌人转向时图像翻转的逻辑 5.去除补丁，重构残血bug处理相关代码 6.动画和Enemysetting参数修改 7.精英怪生成逻辑修改 8.增添中立投射物碰撞体特性
